version: '3.8'

services:
  postgres:
    image: postgres:latest-
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloakdbuser -d keycloakdb -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - keycloak_network

  keycloak:
    image: jboss/keycloak:latest
    container_name: local_keycloak
    ports:
      - 8080:8080
    volumes:
      - ./data:/opt/jboss/keycloak/standalone/data
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: ${POSTGRESQL_PORT}
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 240s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak_network

networks:
  keycloak_network: